options:
  OPENBW_ENABLE_UI: 0
  # You may override this through command line environment options
  # BWAPI_INSTALL_PREFIX: ~/Public/bwapi
  BWAPI_INSTALL_PREFIX: ~/Documents/ic3_torchcraft/bwapi
  # Replace with your own starcraft map
  BWAPI_CONFIG_AUTO_MENU__MAP: ../gym-starcraft/maps/micro-empty.scm
  
  # BWAPI_CONFIG_AI__AI: BWEnv/build/BWEnv.so
  BWAPI_CONFIG_AI__AI: BWEnv/build/BWEnv.dylib # For mac replace with this